### ISSUE TITLE
Не экспортируются правила МСЭ с Checkpoint

### ISSUE THREAD

**Issue by mz0b** [usergate/Migrations#5]
Собственно, сабж. Пэкэдж экспортируется только частично, к примеру списки IP-адресов экспортируются, а правила МСЭ - нет. В логе экспорта ошибок нет, как будто утилита просто проигнорировала этот раздел. Прошу подсказать, куда копать.

Пэкэдж снят с Checpoint SMS 80.40, версия утилиты последняя.

**Comment by ran1024** [comment]
Исправлено в версии 3.3
