### ISSUE TITLE
Отсутствует mclib в universal_converter

### ISSUE THREAD

**Issue by FrankSandow** [usergate/Migrations#6]
Отсутствует файл mclib.py, импортируемый в vizard_classes.py:
`from mclib import McXmlRpc`
Также можно ли для поддержки Windows открывать файлы с параметром `encoding="utf-8"`, например `with open(json_file, 'w', encoding="utf-8") as fh:`?

**Comment by ran1024** [comment]
Заведите тикет в тех.поддержку UserGate.
