### ISSUE TITLE
Не отправляет настройки на UG

### ISSUE THREAD

**Issue by Acc1p1ter-art** [usergate/Migrations#7]
1) Конфиги выгружены с Cisco ASA
2) Открыт Импорт на UG
3) Выбрана папка Libraries
4) Введён IP, Логин и Пароль от UT, при этом UG активирован, выполнены базовые настройки по Readme от утилиты
5) Конвертер подключился к UG и приступает к считыванию настроек, выполняет их за 5 секунд, пишет об успешном завершении, столбец слева становится пустым, при нажатии "Импортировать всё" пишет, что импорт успешен, при этом в настройках UG ничего не появляется, при нажатии на "Импорт выбранного раздела" пишет, что раздел не выбран.
![image](https://github.com/usergate/Migrations/assets/173878012/ac0011e0-c92b-4347-a489-8d3c103d769e)

**Comment by Acc1p1ter-art** [comment]
![image](https://github.com/usergate/Migrations/assets/173878012/1406c0ee-0cbd-4abd-8ad6-1141db1c5fd3)

**Comment by Acc1p1ter-art** [comment]
![image](https://github.com/usergate/Migrations/assets/173878012/4c44bdea-e33b-45b7-8644-0c81f7025d5d)

**Comment by ran1024** [comment]
Вы не прочитали инструкцию по применению и соответственно не правильно указали каталог с конфигурацией.

**Comment by ran1024** [comment]
Вы не прочитали инструкцию по применению и соответственно не правильно указали каталог с конфигурацией.
